-- 0003_reported_warnings: stores Waze-style user-reported sensory warnings (waypoints).
--
-- Column details:
--   id           -> unique ID generated by client/server (e.g. w_user_123456)
--   username     -> user who submitted the report
--   warning_type -> type of sensory warning: 'sound' | 'heat' | 'smell' | 'crowds' | 'other'
--   title        -> warning title (e.g. 'Loud Drilling')
--   description  -> description of impact
--   lat / lon    -> coordinates where the warning was reported
--   created_at   -> timestamp of reporting (used for expiration calculations)

CREATE TABLE IF NOT EXISTS reported_warnings (
    id           text PRIMARY KEY,
    username     text NOT NULL,
    warning_type text NOT NULL,
    title        text NOT NULL,
    description  text NOT NULL,
    lat          double precision NOT NULL,
    lon          double precision NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now()
);
