name: Test Project

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    container: 
      image: siva123134/drp10:latest

    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: echo "hello, test!"