name: Test Project

on:
  push:
    branches:
      -main 

jobs:
  build:
    runs-on: ubunutu-latest 

    steps:
      -uses: actions/checkout@v4
      -runs: ls -la
      -runs: echo "hello, test!"